import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
        colors: {
            "secondary-dim": "#005e58",
            "surface-bright": "#f7f9fb",
            "on-primary-fixed": "#022c22",
            "on-secondary-fixed": "#004843",
            "error-dim": "#4f0116",
            "on-tertiary": "#faf8ff",
            "on-error": "#fff7f7",
            "outline-variant": "#a9b4b9",
            "on-error-container": "#782232",
            "primary-container": "#d1fae5",
            "on-surface-variant": "#566166",
            "on-primary": "#ffffff",
            "surface-dim": "#cfdce3",
            "on-tertiary-container": "#474d67",
            "surface-container-high": "#e1e9ee",
            "primary-dim": "#059669",
            "error-container": "#ff8b9a",
            "inverse-on-surface": "#9a9d9f",
            "surface-container-highest": "#d9e4ea",
            "on-tertiary-fixed-variant": "#505771",
            "tertiary-dim": "#4b526c",
            "tertiary-fixed-dim": "#c7ceec",
            "on-surface": "#2a3439",
            "on-secondary-container": "#005c56",
            surface: "#f7f9fb",
            "secondary-fixed": "#8ff4ea",
            "secondary-container": "#8ff4ea",
            "on-background": "#2a3439",
            outline: "#717c82",
            "inverse-surface": "#0b0f10",
            "secondary-fixed-dim": "#80e5dc",
            "on-primary-container": "#064e3b",
            "surface-tint": "#10b981",
            "primary-fixed": "#a7f3d0",
            "surface-variant": "#d9e4ea",
            "inverse-primary": "#34d399",
            "surface-container": "#e8eff3",
            "on-primary-fixed-variant": "#047857",
            tertiary: "#575e78",
            "tertiary-fixed": "#d5dcfb",
            "on-secondary": "#e1fffa",
            "primary-fixed-dim": "#6ee7b7",
            error: "#9e3f4e",
            "on-secondary-fixed-variant": "#006761",
            background: "#f7f9fb",
            primary: "#10b981",
            "on-tertiary-fixed": "#343b53",
            "surface-container-low": "#f0f4f7",
            "surface-container-lowest": "#ffffff",
            "tertiary-container": "#d5dcfb",
            secondary: "#006b64",
        },
        fontFamily: {
            headline: ["Manrope", "sans-serif"],
            body: ["Inter", "sans-serif"],
        },
        },
    },
    plugins: [],
};

export default config;